 # -*- coding: utf-8 -*-
 
class AnalysisStringsEN:
 
   REPORT_TITLE = "DROID Analysis Results"
   REPORT_SUMMARY = "Summary Statistics" 
   REPORT_VERSION = "Analysis Version"
   REPORT_FILE = "Analysis File"
   
   REPORT_MORE_INFORMATION = "Summary of the Statistic"
   
   SUMMARY_TOTAL_FILES = "Total Files" 
   SUMMARY_ARCHIVE_FILES = "Total Archive Files" 
   SUMMARY_INSIDE_ARCHIVES = "Total Files Inside Archive Objects" 
   SUMMARY_DIRECTORIES = "Total Directories" 
   SUMMARY_UNIQUE_DIRNAMES = "Total Unique Directory Names" 
   SUMMARY_IDENTIFIED_FILES = "Total Identified Files (Based on Signature)"
   SUMMARY_MULTIPLE = "Total Multiple Identifications (Baed on Signature)"
   SUMMARY_UNIDENTIFIED = "Total Unidentified Files" 
   SUMMARY_EXTENSION_ID = "Total Extension ID Only Count"
   SUMMARY_EXTENSION_MISMATCH = "Total Extension Mismatches" 
   SUMMARY_ID_PUID_COUNT = "Total Signature ID'd PUID Count"
   SUMMARY_UNIQUE_EXTENSIONS = "Total Unique Extensions Across Accession/Extract"
   SUMMARY_ZERO_BYTE = "Total Zero-byte Files in Accession/Extract" 
   SUMMARY_IDENTICAL_FILES = "Total Files with Identical Content (Checksum Value)"
   SUMMARY_MULTIPLE_SPACES = "Total Files with Multiple Contiguous Space Characters"
   SUMMARY_PERCENTAGE_IDENTIFIED = "Percentage of Accession/Extract Identified"
   SUMMARY_PERCENTAGE_UNIDENTIFIED = "Percentage of Accession/Extract Unidentified"
   
   HEADING_SIZE = "Size of the Collection on Disk"
   HEADING_IDENTIFIED = "Identified File Formats in Accession/Extract" 
   HEADING_FREQUENCY_PUIDS_IDENTIFIED = "Frequency of File Format Signature Identified PUIDs"
   HEADING_DATE_RANGE = "Date Range of Items in the Accession/Extract"
   HEADING_EXTENSION_ONLY = "Extension Only Identification in the Accession/Extract"
   HEADING_ID_METHOD = "Identification Method Frequency" 
   HEADING_FREQUENCY_EXTENSION_ONLY = "Frequency of Extension Only Identification In Accession/Extract" 
   HEADING_UNIQUE_EXTENSIONS = "Unique Extensions Identified Across All Objects (ID and non-ID)"
   HEADING_LIST_MULTIPLE = "List of Files With Multiple Identifications" 
   HEADING_FREQUENCY_EXTENSIONS_ALL = "Frequency of All Extensions"
   HEADING_FREQUENCY_MIME = "MIME Type (Internet Media Type) Frequency"
   HEADING_LIST_ZERO_BYTES = "Zero-byte files in Accession/Extract" 
   HEADING_NO_ID = "Files With No Identification"
   HEADING_ARCHIVE_FORMATS = "Archive Format Types in Accession/Extract"
   HEADING_IDENTICAL_CONTENT = "Files With Identical Content" 
   HEADING_TROUBLESOME_FILENAMES = "Identifying Troublesome Filenames" 

   SUMMARY_DESC_TOTAL_FILES = "AAAA" 
   SUMMARY_DESC_ARCHIVE_FILES = "BBBB" 
   SUMMARY_DESC_INSIDE_ARCHIVES = "CCCC" 
   SUMMARY_DESC_DIRECTORIES = "DDDD" 
   SUMMARY_DESC_UNIQUE_DIRNAMES = "EEEE" 
   SUMMARY_DESC_IDENTIFIED_FILES = "FFFF"
   SUMMARY_DESC_MULTIPLE = "GGGG"
   SUMMARY_DESC_UNIDENTIFIED = "HHHH" 
   SUMMARY_DESC_EXTENSION_ID = "IIII"
   SUMMARY_DESC_EXTENSION_MISMATCH = "JJJJ" 
   SUMMARY_DESC_ID_PUID_COUNT = "KKKK"
   SUMMARY_DESC_UNIQUE_EXTENSIONS = "LLLL"
   SUMMARY_DESC_ZERO_BYTE = "MMMM" 
   SUMMARY_DESC_IDENTICAL_FILES = "NNNN"
   SUMMARY_DESC_MULTIPLE_SPACES = "OOOO"
   SUMMARY_DESC_PERCENTAGE_IDENTIFIED = "PPPP"
   SUMMARY_DESC_PERFENTAGE_UNIDENTIFIED = "QQQQ"
   
   HEADING_DESC_SIZE = "0000"
   HEADING_DESC_IDENTIFIED = "RRRR" 
   HEADING_DESC_FREQUENCY_PUIDS_IDENTIFIED = "SSSS"
   HEADING_DESC_DATE_RANGE = "TTTT"
   HEADING_DESC_EXTENSION_ONLY = "UUUU"
   HEADING_DESC_ID_METHOD = "VVVV" 
   HEADING_DESC_FREQUENCY_EXTENSION_ONLY = "WWWW" 
   HEADING_DESC_UNIQUE_EXTENSIONS = "XXXX"
   HEADING_DESC_LIST_MULTIPLE = "YYYY" 
   HEADING_DESC_FREQUENCY_EXTENSIONS_ALL = "ZZZZ"
   HEADING_DESC_FREQUENCY_MIME = "ABAB"
   HEADING_DESC_LIST_ZERO_BYTES = "CDCD" 
   HEADING_DESC_NO_ID = "EFEF"
   HEADING_DESC_ARCHIVE_FORMATS = "GHGH"
   HEADING_DESC_IDENTICAL_CONTENT = "IJIJ" 
   HEADING_DESC_TROUBLESOME_FILENAMES = "KLKL"    
