testcsv = [
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"test-empty-folders",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders",
        u"FORMAT_NAME": u"",
        u"ID": u"1",
        u"PARENT_ID": u"",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:34:37",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"empty_folder_a",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_a",
        u"FORMAT_NAME": u"",
        u"ID": u"2",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:14:39",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_a/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"empty_folder_b",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_b",
        u"FORMAT_NAME": u"",
        u"ID": u"3",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:14:45",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_b/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"empty_folder_with_empty_folder",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_with_empty_folder",
        u"FORMAT_NAME": u"",
        u"ID": u"4",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:15:09",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_with_empty_folder/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"empty_folder_inside_empty_folder",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\empty_folder_with_empty_folder\\empty_folder_inside_empty_folder",
        u"FORMAT_NAME": u"",
        u"ID": u"5",
        u"PARENT_ID": u"4",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:15:04",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/empty_folder_with_empty_folder/empty_folder_inside_empty_folder/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"folder-becomes-empty-one-file",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-becomes-empty-one-file",
        u"FORMAT_NAME": u"",
        u"ID": u"6",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:15:56",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-becomes-empty-one-file/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"folder-wont-empty-extension-based",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-wont-empty-extension-based",
        u"FORMAT_NAME": u"",
        u"ID": u"7",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:34:48",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-wont-empty-extension-based/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"folders-become-empty-two-files-inside-other-folder",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder",
        u"FORMAT_NAME": u"",
        u"ID": u"9",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:17:06",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"sub-folder-becomes-empty",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty",
        u"FORMAT_NAME": u"",
        u"ID": u"11",
        u"PARENT_ID": u"9",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:17:29",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"folders-wont-become-empty-two-files-inside-other-folder-plus-one",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one",
        u"FORMAT_NAME": u"",
        u"ID": u"12",
        u"PARENT_ID": u"1",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:17:45",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"sub-folder-wont-become-empty",
        u"PUID": u"",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty",
        u"FORMAT_NAME": u"",
        u"ID": u"15",
        u"PARENT_ID": u"12",
        u"EXT": u"",
        u"LAST_MODIFIED": u"2015-07-22T13:18:27",
        u"FORMAT_COUNT": u"",
        u"MD5_HASH": u"",
        u"FORMAT_VERSION": u"",
        u"TYPE": u"Folder",
        u"METHOD": u"",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/",
        u"SIZE": u"",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-becomes-empty-one-file\\thumbs.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"8",
        u"PARENT_ID": u"6",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:15:35",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Container",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-becomes-empty-one-file/thumbs.db",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.1.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty\\thumbs.1.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"14",
        u"PARENT_ID": u"11",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:17:12",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Container",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/thumbs.1.db",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.2.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-become-empty-two-files-inside-other-folder\\sub-folder-becomes-empty\\thumbs.2.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"13",
        u"PARENT_ID": u"11",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:17:25",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Container",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-become-empty-two-files-inside-other-folder/sub-folder-becomes-empty/thumbs.2.db",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folder-wont-empty-extension-based\\thumbs.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"10",
        u"PARENT_ID": u"7",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:34:45",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Extension",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folder-wont-empty-extension-based/thumbs.db",
        u"SIZE": u"10",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.2.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\thumbs.2.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"17",
        u"PARENT_ID": u"15",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:17:25",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Container",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/thumbs.2.db",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"",
        u"NAME": u"thumbs.1.db",
        u"PUID": u"fmt/682",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\thumbs.1.db",
        u"FORMAT_NAME": u"Thumbs DB file",
        u"ID": u"16",
        u"PARENT_ID": u"15",
        u"EXT": u"db",
        u"LAST_MODIFIED": u"2015-07-22T13:17:12",
        u"FORMAT_COUNT": u"1",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"XP",
        u"TYPE": u"File",
        u"METHOD": u"Signature",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/thumbs.1.db",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"application/msword",
        u"NAME": u"word-document1.doc",
        u"PUID": u"fmt/39",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\word-document1.doc",
        u"FORMAT_NAME": u"Microsoft Word",
        u"ID": u"18",
        u"PARENT_ID": u"15",
        u"EXT": u"doc",
        u"LAST_MODIFIED": u"2015-07-22T13:18:23",
        u"FORMAT_COUNT": u"8",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"6.0-2003",
        u"TYPE": u"File",
        u"METHOD": u"Signature",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/word-document1.doc",
        u"SIZE": u"0",
    },
    {
        u"STATUS": u"Done",
        u"MIME_TYPE": u"application/msword",
        u"NAME": u"word-document.doc",
        u"PUID": u"fmt/39",
        u"EXTENSION_MISMATCH": u"FALSE",
        u"FILE_PATH": u"C:\\Documents and Settings\\spencero\\Desktop\\test-empty-folders\\folders-wont-become-empty-two-files-inside-other-folder-plus-one\\sub-folder-wont-become-empty\\word-document.doc",
        u"FORMAT_NAME": u"Microsoft Word",
        u"ID": u"18",
        u"PARENT_ID": u"15",
        u"EXT": u"doc",
        u"LAST_MODIFIED": u"2015-07-22T13:18:23",
        u"FORMAT_COUNT": u"8",
        u"MD5_HASH": u"d41d8cd98f00b204e9800998ecf8427e",
        u"FORMAT_VERSION": u"6.0-2003",
        u"TYPE": u"File",
        u"METHOD": u"Signature",
        u"URI": u"file:/C:/Documents%20and%20Settings/spencero/Desktop/test-empty-folders/folders-wont-become-empty-two-files-inside-other-folder-plus-one/sub-folder-wont-become-empty/word-document.doc",
        u"SIZE": u"0",
    },
]
